git checkout main
name: final_year_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  table_calendar: ^3.0.7
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
=======
  syncfusion_flutter_calendar: ^20.2.50
>>>>>>> 2663f534a7ecd2ecb2a008f9e4d6defcda1f21f3

  cupertino_icons: ^1.0.2
  pie_chart: ^5.3.2
  fl_chart: ^0.55.0
  syncfusion_flutter_charts: ^20.2.39
  localization: ^2.1.0
  intl: ^0.17.0
  syncfusion_flutter_calendar: ^20.3.56
  google_sign_in: ^5.4.2
  provider: ^6.0.4
  font_awesome_flutter: ^10.2.1
  cloud_firestore: ^4.0.5
  pay: ^1.0.11
  upi_india: ^3.0.1
  razorpay_flutter: ^1.2.1
  http: ^0.13.5
  flutter_local_notifications: ^12.0.3+1
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
=======
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
>>>>>>> 2663f534a7ecd2ecb2a008f9e4d6defcda1f21f3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

<<<<<<< HEAD
  assets:
    - assets/Images/
    - assets/Images/Services/Plumber/image 71.png
    - assets/Images/Services/Plumber/image 73.png
    - assets/Images/Services/Plumber/image 76.png
    - assets/Images/Services/Plumber/background.png
    - assets/gpay.json
    - assets/Images/Login/image 3.png
    - assets/Images/Login/Trees.png
    - assets/Images/Welcome/WelcomeImage.png
=======
  # To add assets to your application, add an assets section, like this:
assets:
  - assets\images

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
>>>>>>> 2663f534a7ecd2ecb2a008f9e4d6defcda1f21f3
